### ISSUE TITLE
Multi-contig gff parsing: Range issue

### ISSUE THREAD

**Issue by acarafat** [moshi4/pyCirclize#33]
### Discussed in https://github.com/moshi4/pyCirclize/discussions/32

<div type='discussions-op-text'>

<sup>Originally posted by **acarafat** August 22, 2023</sup>
I am working with a GFF file that contains multiple contigs, but the `##sequence-region` only shows for the contig 1 in the gff header info. 

Currently, while using `.get_seqid2size()` from gff parser, present code relies on `##sequence-region` tag, therefore it gets the range for rest of the contigs wrong. 

It could be solved by not relying on the `##sequence-region`, since many gff file generated by different programs may not contain this comment.
  </div>

**Comment by moshi4** [comment]
Hi @acarafat,

Thank you for reporting this issue.

Looking back at the code of the Gff parser, as you said, if there is no `##sequence-region` tag, it was not getting the contig range correctly.

There was a bug in the code that assumed the absence of the `##sequence-region` tag.
Since it does not work as expected, I will release a fixed version as v0.5.1 soon. Please wait a moment.

**Comment by acarafat** [comment]
Hello, I'm just realized that the .gbk parser also has the same issue. 

Best, 
Arafat

**Comment by moshi4** [comment]
There is no `##sequence-region` tag in the Genbank file.
Without additional explanation, I am not sure what **same issue** means.
