### ISSUE TITLE
Phylogenetic leaf labels with spaces are truncated

### ISSUE THREAD

**Issue by dnjst** [moshi4/pyCirclize#42]
Thank you so much for this terrific package and congraulations on the 1.0.0 release!

I just had a really quick comment that in a phylogenetic tree with spaces in the node labels, it seems they are displayed with only the last part after the space,

for instance

"PV AOC3" becomes "AOC3".

**Comment by moshi4** [comment]
In newick format files, it is deprecated to include spaces in node names. 
pyCirclize uses BioPython to parse the newick format phylogenetic tree, and BioPython cannot correctly retrieve node names that contain spaces.

Since it is difficult to solve this problem, I recommend changing the space in the node name to underscore in advance.

**Comment by dnjst** [comment]
Got it, thank you very much!
