### ISSUE TITLE
Issue with ZeroDivisionError in Circos Plot

### ISSUE THREAD

**Issue by MattFill** [moshi4/pyCirclize#49]
Firstly, thank you for this outstanding circular visualization package.

However, I've encountered an issue while attempting to create a circos plot. I'm aiming for something similar to Example 4-2 in your documentation. My dataset consists of a 'to-from' table that includes approximately 37,000 entries, many of which are zeros. While using the following code to generate the circos diagram, I encounter a "ZeroDivisionError: float division by zero":

```
from pycirclize.parser import Matrix
matrix = Matrix.parse_fromto_table(tmp_weights)

circos = Circos.initialize_from_matrix(
    matrix,
    space=3,
    cmap="viridis",
    ticks_interval=5,
    label_kws=dict(size=12, r=110),
    link_kws=dict(direction=1, ec="black", lw=0.5),
)

fig = circos.plotfig()
```

I'm curious about the potential cause of this error. Could it be related to the size of my matrix or its sparsity? Any insights or suggestions you could provide would be immensely helpful.

**Comment by Zymeth0211** [comment]
I was too having that problem.
But when I checked my matrix data for link plot. I realized a problem due to zero link.
I deleted columns that have 0 value on all indexes.
Here's my data
![image](https://github.com/moshi4/pyCirclize/assets/155029380/f8fb911a-ec11-4a44-a984-10d95250327b)
That is Okay.

But if you have one or more columns containing all 0. You need to delete that column. I hope you could understand.

**Comment by moshi4** [comment]
Hi @MattFill 

> My dataset consists of a 'to-from' table that includes approximately 37,000 entries, many of which are zeros.

If you remove all data with a value of 0 from the "from-to" table, the ZeroDivisionError should not occur.

**Comment by MengxingLiu** [comment]
Hi @moshi4 
thanks for this beautiful package. is there any chance it supports all zero rows/columns so that it circos plot has this label appearing on the plot only with no connections? 
The rational behind this is that pairs not showing on the plot can be not tested or not positive, but if it shows on the plot, meaning it's tested, but not positive.
