### ISSUE TITLE
Doubt regarding pycircilize

### ISSUE THREAD

**Issue by Thallam-Prashanth** [moshi4/pyCirclize#59]
Sir when I plot my time series data using pycircilize. the circos line plot is not showing the variation. for example my data is lies between 433 to 435. The Circos line plot is showing straight line i.e. there is no variation in timeseries. In pycircilize, there is no yticks why??

**Comment by moshi4** [comment]
I don't know which plot method you are using, but are you setting the vmin argument of your method correctly?
By default vmin=0, so your figure may be plotting in the y range 0-435 instead of 433-435.

If setting vmin does not solve the problem, please provide your code. 
Without seeing the code, it is difficult to determine what the problem is.

**Comment by Thallam-Prashanth** [comment]
Respected sir please find attached python code and data and we had google colab to run the code. Please help me out by setting vmin as minimum of its timeseries sir.

[Chrid.csv](https://github.com/moshi4/pyCirclize/files/14399716/Chrid.csv)
[Chrid21.csv](https://github.com/moshi4/pyCirclize/files/14399717/Chrid21.csv)
[circilize code.txt](https://github.com/moshi4/pyCirclize/files/14399739/circilize.code.txt)

**Comment by moshi4** [comment]
Please do not throw "whole" tasks at me that you should solve yourself.
I am not your personal tutor and I am not willing to spend my time to help you that much.

When asking for help with your own task, you should try to keep the question to a smaller scope so that it is easier for the respondent to answer. Specifically, instead of throwing in all of your code and input data, you should present only a portion of the code and input data in question in a way that is easy to understand.

I am not going to answer this question because it does not provide enough information to answer it and is quite burdensome.
