### ISSUE TITLE
How can I add small circles of different sizes in each grid of a heatmap?

### ISSUE THREAD

**Issue by wyxxxj** [moshi4/pyCirclize#69]
Can we add circles of different sizes in each grid of a heatmap? If so, could you please provide an example? Thank you!
![JOH-1](https://github.com/moshi4/pyCirclize/assets/148619904/ce4c2aab-f8e7-4b0e-a2f8-369cab667a1c)

**Comment by moshi4** [comment]
Hi @wyxxxj,

Although I could not plot a similar legend, it was possible to plot circles of different sizes on the heatmap grid.
It seems difficult to set the appropriate circle size, so it would be a challenge to visualize the analysis results in this plot format. Due to the difficulty of the plot, I do not intend to provide further support, but good luck.

**Code Example**

```python
from pycirclize import Circos
import numpy as np
np.random.seed(0)

# Create 10 - 100 random values (8 x 80) 2d-array
darray = np.random.randint(10, 100 + 1, (8, 80))

# Plot heatmap
x_size, y_size = darray.shape[1], darray.shape[0]
circos = Circos(dict(heatmap=x_size))
sector = circos.sectors[0]
track = sector.add_track((50, 100))
track.heatmap(darray, vmin=0, vmax=100, cmap="Oranges")

# Plot circle on heatmap rect
for i in range(y_size):
    for j in range(x_size):
        v = darray[i][j]
        x, y = j + 0.5, y_size - i - 0.5
        # Circle size(s) is defined based on 2d-array value
        # In the actual data analysis, some sort of correction would need to be applied to determine the circle size.
        track.scatter([x], [y], s=v, vmin=0, vmax=y_size, fc="none", ec="black", lw=0.5)

circos.savefig("example.png")
```

**example.png**

![example](https://github.com/moshi4/pyCirclize/assets/41852815/13d775e5-f7b1-4412-b275-4b54b4c36684)

**Comment by wyxxxj** [comment]
Thank you very much for your reply！I have successfully drawn the graph！
