### ISSUE TITLE
CLI usage & citation

### ISSUE THREAD

**Issue by abubelinha** [moshi4/pyCirclize#7]
I use python in command line interface and I don't know how to show the plotted figure like when using `matplotlib.pyplot.show()` (I saw in other scripts but I have not experience with matplotlib either).

I added [`fig.show()`](https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.show) at the end of one of your examples, and figure is displayed by python but immediately closed.
I can save it with `circos.savefig("myfile.png")` and then open with another program, but I'd prefer it to open automatically when running script, and keep open until I close the viewer.

Also, I would like to know what is the suggested way to citate your work in a publication.

Thanks a lot !

**Comment by moshi4** [comment]
It doesn't work with `fig.show()` because the GUI event loop is not fired. I think you should use `plt.show()` instead. It works fine that way in my environment. You can find an explanation related to the matplotlib GUI window in this [document](https://matplotlib.org/stable/users/explain/interactive.html).

Here is an example code.

```python
import matplotlib.pyplot as plt

from pycirclize import Circos

sectors = {"A": 10, "B": 20, "C": 15}
circos = Circos(sectors, space=5)
for sector in circos.sectors:
    sector.text(sector.name)
    track = sector.add_track((90, 100))
    track.axis()
fig = circos.plotfig()

plt.show()
```

___

> Also, I would like to know what is the suggested way to citate your work in a publication.

As shown below, the suggested citation can be found from the repository top screen.

![Screenshot from 2023-02-01 10-11-18](https://user-images.githubusercontent.com/41852815/215921709-e75c4321-b3ce-4d6f-84b9-671535da4363.png)

**Comment by abubelinha** [comment]
Thanks a lot for comments and links. 
`plt.show()` works perfectly for me too. 👍 

I guess the citation link must be shown only with modern desktop browsers. 
I can see it now at work (Windows 10, Chrome), but not at home (desktop Win 7, ipad air 2 tablet).
Can you see with mobile phone browser? (I can't find it there, unless I select desktop view).
